version: '3.7'

services:
  stats:
    image: docker.io/bitnami/rabbitmq:3.10
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == mdodb-master
      restart_policy:
        condition: on-failure
    environment:
      - RABBITMQ_NODE_TYPE=stats
      - RABBITMQ_NODE_NAME=rabbit_stats
      - RABBITMQ_ERL_COOKIE=mdo@123
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
    ports:
      - '15672:15672'
    networks:
      - dwsnet  
    volumes:
      - 'stats_data:/bitnami/rabbitmq/mnesia'
  queuedisc1:
    image: docker.io/bitnami/rabbitmq:3.10
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == mdodb-slave
      restart_policy:
        condition: on-failure
    ports:
      - '5678:5672'
    networks:
      - dwsnet
    environment:
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=queuedisc1
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit_stats
      - RABBITMQ_ERL_COOKIE=mdo@123
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
    volumes:
      - 'queuedisc1_data:/bitnami/rabbitmq/mnesia'
  queuedisc2:
    image: docker.io/bitnami/rabbitmq:3.10
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == mdodb-slave
      restart_policy:
        condition: on-failure
    ports:
      - '5679:5672'
    networks:
      - dwsnet
    environment:
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=queuedisc2
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit_stats
      - RABBITMQ_ERL_COOKIE=mdo@123
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
    volumes:
      - 'queuedisc2_data:/bitnami/rabbitmq/mnesia'    
  # queue-ram1:
  #   image: docker.io/bitnami/rabbitmq:3.10
  #   ports:
  #     - '5679:5672'
  #   networks:
  #     - dwsnet
  #   environment:
  #     - RABBITMQ_NODE_TYPE=queue-ram
  #     - RABBITMQ_NODE_NAME=rabbit@queue-ram1
  #     - RABBITMQ_CLUSTER_NODE_NAME=rabbit@stats
  #     - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
  #     - RABBITMQ_SECURE_PASSWORD=yes
  #     - RABBITMQ_LOGS=-
  #   volumes:
  #     - 'rabbitmqram1_data:/bitnami/rabbitmq/mnesia'
networks:
  dwsnet:
    external: true
volumes:
  stats_data:
    driver: local
  queuedisc1_data:
    driver: local
  queuedisc2_data:
    driver: local